//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.PR.Data.AdService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdService.IAdService")]
    public interface IAdService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetRandomBiilBoards", ReplyAction="http://tempuri.org/IAdService/GetRandomBiilBoardsResponse")]
        object GetRandomBiilBoards();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetRandomBiilBoards", ReplyAction="http://tempuri.org/IAdService/GetRandomBiilBoardsResponse")]
        System.Threading.Tasks.Task<object> GetRandomBiilBoardsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdServiceChannel : DM.PR.Data.AdService.IAdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdServiceClient : System.ServiceModel.ClientBase<DM.PR.Data.AdService.IAdService>, DM.PR.Data.AdService.IAdService {
        
        public AdServiceClient() {
        }
        
        public AdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object GetRandomBiilBoards() {
            return base.Channel.GetRandomBiilBoards();
        }
        
        public System.Threading.Tasks.Task<object> GetRandomBiilBoardsAsync() {
            return base.Channel.GetRandomBiilBoardsAsync();
        }
    }
}
