//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM.PR.Data.AdServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdServiceClient.IAdService")]
    public interface IAdService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetContent", ReplyAction="http://tempuri.org/IAdService/GetContentResponse")]
        string[] GetContent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetContent", ReplyAction="http://tempuri.org/IAdService/GetContentResponse")]
        System.Threading.Tasks.Task<string[]> GetContentAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdServiceChannel : DM.PR.Data.AdServiceClient.IAdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdServiceClient : System.ServiceModel.ClientBase<DM.PR.Data.AdServiceClient.IAdService>, DM.PR.Data.AdServiceClient.IAdService {
        
        public AdServiceClient() {
        }
        
        public AdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetContent() {
            return base.Channel.GetContent();
        }
        
        public System.Threading.Tasks.Task<string[]> GetContentAsync() {
            return base.Channel.GetContentAsync();
        }
    }
}
